Fix Kconfig support check

diff --git a/hal/Makefile b/hal/Makefile
--- a/hal/Makefile
+++ b/hal/Makefile
@@ -1,18 +1,13 @@
 -include $(HAL_DIR)/Makefile
 
-checkconfig:
-		@if [ "$(CONFIG_GPIO)" ] && [ "$(CONFIG_PLATFORM_SUPPORTS_GPIO)" != "y" ]; then \
-        echo "Error: Platform does not support GPIO"; \
-				exit 1; \
-		fi
-		@if [ "$(CONFIG_UART)" ] && [ "$(CONFIG_PLATFORM_SUPPORTS_UART)" != "y" ]; then \
-        echo "Error: Platform does not support UART"; \
-				exit 1; \
-		fi
-		@if [ "$(CONFIG_USB)" ] && [ "$(CONFIG_PLATFORM_SUPPORTS_USB)" != "y" ]; then \
-        echo "Error: Platform does not support USB"; \
-				exit 1; \
-		fi
+HAL_MODULES  := GPIO UART USB
+
+CHECK_KCONFIG += $(foreach module,$(HAL_MODULES), \
+	if [ "$(CONFIG_$(module))" ] && [ "$(CONFIG_PLATFORM_SUPPORTS_$(module))" != "y" ]; then \
+		echo "Error: Platform does not support $(module)"; \
+		exit 1; \
+	fi;)
+
 
 ifeq ($(CONFIG_GPIO),y)
 SOURCES += $(HAL_DIR)/gpio.c
